// Contract addresses - Auto-generated by deploy script
// Deployed to Monad Testnet: 2026-02-15
// Tokens are launched via Nad.fun — no GENToken contract needed

const ZERO = "0x0000000000000000000000000000000000000000" as `0x${string}`;

export const TESTNET_ADDRESSES = {
  GENMON_REGISTRY: "0xe476D00Fb8b2f3ed933DA9112D460F26f4FE38A9" as `0x${string}`,
  EVOLUTION_ENGINE: "0xe888DD9912536baBeB1417fa6C6c6063Cd009854" as `0x${string}`,
  LAUNCH_EXECUTOR: "0x8c9133b4D531B01878fBF4b3e346C5aF1D509925" as `0x${string}`,
  TREASURY_MANAGER: "0x98a1Af29Fe187db829421F118eA203674E2CACee" as `0x${string}`,
} as const;

export const MAINNET_ADDRESSES = {
  GENMON_REGISTRY: ZERO as `0x${string}`,
  EVOLUTION_ENGINE: ZERO as `0x${string}`,
  LAUNCH_EXECUTOR: ZERO as `0x${string}`,
  TREASURY_MANAGER: ZERO as `0x${string}`,
} as const;

export function getContractAddresses(chainId: number) {
  if (chainId === 143) return { addresses: MAINNET_ADDRESSES, deployed: false };
  return { addresses: TESTNET_ADDRESSES, deployed: true };
}

export const CONTRACT_ADDRESSES = TESTNET_ADDRESSES;
export const CONTRACTS_DEPLOYED = true;
